#!/bin/bash

# Igor Duarte Cardoso
# 1.0.2 - 20140320

usage() {
    echo "Usage: "
    echo "  wundermail <user email address> <file with task list>"
    echo "Example: "
    echo "  wundermail joe.maximus@gmail.com my-task-list.txt"
    echo "Requirements: "
    echo "  mailx"
    exit
}

function wundermail() {
    from=$1
    user=$1
    subject=$2
    body=$3
    passw=$4

    to=me@wunderlist.com
    smtp_addr=smtp.gmail.com
    smtp_port=587

    opts="-S smtp-use-starttls \
    -S ssl-verify=ignore \
    -S smtp-auth=login \
    -S smtp=smtp://$smtp_addr:$smtp_port \
    -S from=$from \
    -S smtp-auth-user=$user \
    -S smtp-auth-password=$passw \
    -S ssl-verify=ignore"

    echo "$body" | mailx -s "$subject" -v $opts $to 1> /dev/null 2> /dev/null
}

if [ $# -lt 2 ]; then
  usage
fi

stty -echo </dev/tty;
read -p "SMTP Password: " passw < /dev/tty
echo
stty </dev/tty echo

i=0
while read p || [ -n "$p" ]; do
    ((i++))
    echo "Sending task "$i": "$p"..."
    wundermail "$1" "$p" "$p" "$passw"
    if [ $? -eq 0 ]
    then
        echo "Task "$i" sent successfully!"
    else
        echo "Failed to send task "$i", is the email configuration/password correct?"
    fi
done < "$2"

